api:
  id: "20119572"  # Auto-discovery

mule:
  env: "dev"    
https:
  port: "8082"
  basepath: "/api"
  readTimeout: "120000" #in Ms
  tls:
    path: "certs/keystore-qtcdev.jks"
    aliasname: "mulesoft_integration"
    password: "![gUDORpUXzeYOzWlikBwGHeuU8YXxqIBs]"  
      
notification:
  client-id: "122453e9ada94639b732609a2b3151c5"
  client-secret: "![A1+4aLgh0FeNrdGWJWwKvB/P/oVThXZdP1YNX2KALMuxodgpTqlJCQ==]"
  env: "463175dd-6e87-4a8e-b2fb-a132d75fe083" #dev enviroment id
  
              